baseurl: 
url: 

include: [
  'scripts/dist/main.bundle.js',
  'scripts/dist/second.bundle.js',

  '.htaccess',
]

exclude: [
  '**/*.DS_Store',
  '**/Thumbs.db',
  'package.json',
  'readme.md',
  'scripts/*',
]

sass:
  style: compressed
  sourcemap: never

source: src
destination: dist
includes_dir: _parts

disable_disk_cache: true
