exclude: [

  '**/*.DS_Store',
  '**/Thumbs.db',
  'package.json',
  'readme.md',

  "scripts/*.*",

  'public/files', # from dev
  'public/demos', # from dev

]

include: [

  'scripts/bundle.js',

]
