baseurl: 
url: 

disable_disk_cache: true

source: src
destination: dist
includes_dir: _parts

sass:
  style: compressed
  sourcemap: never

exclude: [

  '**/*.DS_Store',
  '**/Thumbs.db',
  'package.json',
  'readme.md',

  "scripts/*.*",

]

include: [

  'scripts/bundle.js',
  '.htaccess',

]
