v: 1

baseurl: 
url: 

include: [
  'scripts/dist/main.js',
  'scripts/dist/second.js',

  '.htaccess',
]

exclude: [
  '**/*.DS_Store',
  '**/Thumbs.db',
  'package.json',
  'readme.md',
  'scripts/*',
  'vendor/*',
]

sass:
  style: compressed
  sourcemap: never

source: src
destination: dist

disable_disk_cache: true
