services:
  jekyll:
    image: jvconseil/jekyll-docker:4.3.3
    environment:
      upd: 4.4.1
      gem: jekyll-paginate-v2
      apk: p7zip rsync nano
      npm: esbuild
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - ./system/:/root/
    command: >
      sh -c "apk update && apk add $$apk &&
             gem i jekyll -v $$upd --force &&
             gem i $$gem --force &&
             npm i -g $$npm &&
             tail -f /dev/null"
